server:
  port: 8081
logging:
  level:
    com.neprozorro: INFO

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=neprozorro
#    username: postgres
#    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        order_by:
          default_null_ordering: last

info:
  contacts:
    email: ${CONTACT_EMAIL}
  version: 1.0
  host: ${SERVER_HOST:'http://localhost:8081/'}



