package com.neprozorro.model;

public enum LotStatus {

    CLARIFICATION_PERIOD, WAITING_FOR_ORDER, PREQUALIFICATION, PREQUALIFICATION_APPEAL_PERIOD, FIRST_INTERMEDIATE_STAGE,
    SECOND_INTERMEDIATE_STAGE, AUCTION_PERIOD, QUALIFICATION_PERIOD, QUALIFICATION_PERIOD_APPEAL_PERIOD, PROPOSAL_CONSIDERED,
    PURCHASE_DID_NOTE_TAKE_PLACE, COMPLETED_PURCHASE,AUCTION_IS_CANCELLED
}
